using Content.Client.UserInterface.Controls;
using Content.Shared._Hullrot.FireControl;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Hullrot.FireControl.UI;

[GenerateTypedNameReferences]
public sealed partial class FireControlWindow : FancyWindow
{
    public FireControlWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("fire-control-debug");
    }

    public void UpdateStatus(FireControlConsoleComponent component)
    {
        var label = new Label();
        if (component.Connected)
            label.Text = Loc.GetString("fire-control-window-connected");
        else
            label.Text = Loc.GetString("fire-control-window-disconnected");

        RootBox.DisposeAllChildren();
        RootBox.AddChild(label);
    }
}
