using System.Numerics;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Hullrot.WorldGen.UI;

[GenerateTypedNameReferences]
public sealed partial class WorldZoneMapWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    public WorldZoneMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PlaceMapControl();
    }

    private void PlaceMapControl()
    {
        var map = _entMan.System<WorldZoneAestheticsSystem>().GetCurrentZoneMap();

        // TODO: Display null map
        if (map == null)
        {
            this.Close();
            return;
        }

        var control = new WorldZoneMapControl(map, _entMan);
        control.SetSize = new Vector2(map.GetLength(0) * 32 + 20, map.GetLength(1) * 32 + 20);

        MainScreen.AddChild(control);
    }
}
